# Generated by Django 4.2.16 on 2024-10-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL')),
                ('link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка при наведении')),
                ('routes', models.ManyToManyField(to='route.route')),
            ],
            options={
                'verbose_name': 'Страны',
                'verbose_name_plural': 'Страны',
                'db_table': 'countries',
                'ordering': ['id'],
            },
        ),
    ]
