# Generated by Django 4.2.17 on 2025-01-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='сountry',
            name='image1',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='brewery_images'),
        ),
        migrations.AddField(
            model_name='сountry',
            name='image2',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='brewery_images'),
        ),
    ]
