# Generated by Django 4.2.17 on 2025-01-05 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_сountry_image1_сountry_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сountry',
            name='image2',
        ),
        migrations.AddField(
            model_name='сountry',
            name='news_img',
            field=models.FileField(blank=True, null=True, upload_to='country_images', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='сountry',
            name='image1',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='country_images'),
        ),
    ]
