# Generated by Django 4.2.17 on 2025-01-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_remove_сountry_image2_сountry_news_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сountry',
            name='news_img',
        ),
        migrations.AddField(
            model_name='сountry',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='country_images'),
        ),
    ]
