# Generated by Django 4.2.17 on 2025-01-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_remove_сountry_news_img_сountry_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сountry',
            name='image2',
            field=models.FileField(blank=True, default='100.jpeg', null=True, upload_to='country_images'),
        ),
    ]
