# Generated by Django 4.2.16 on 2024-10-05 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0001_initial'),
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название пивоварни')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адресс')),
                ('map_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на карту')),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Часы работы')),
                ('sait_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='сайт')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка при наведении')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание пивоварни')),
                ('image1', models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='brewery_images')),
                ('image2', models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='brewery_images')),
                ('image3', models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='brewery_images')),
                ('image4', models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='brewery_images')),
                ('image5', models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='brewery_images')),
                ('image6', models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='brewery_images')),
                ('country_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='country.сountry', verbose_name='Категория-страна')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='route.route', verbose_name='Категория-маршрут')),
            ],
            options={
                'verbose_name': 'Пивоварни',
                'verbose_name_plural': 'Пивоварни',
                'db_table': 'breweries',
                'ordering': ['title'],
            },
        ),
    ]
