# Generated by Django 4.2.17 on 2025-01-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewery',
            options={'ordering': ['id'], 'verbose_name': 'Пивоварни', 'verbose_name_plural': 'Пивоварни'},
        ),
        migrations.AddField(
            model_name='brewery',
            name='descript_full',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание пивоварни полное'),
        ),
        migrations.AddField(
            model_name='brewery',
            name='image10',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='brewery_images'),
        ),
        migrations.AddField(
            model_name='brewery',
            name='image7',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='brewery_images'),
        ),
        migrations.AddField(
            model_name='brewery',
            name='image8',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='brewery_images'),
        ),
        migrations.AddField(
            model_name='brewery',
            name='image9',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='brewery_images'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание пивоварни'),
        ),
    ]
