# Generated by Django 4.2.16 on 2024-10-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='city_desc',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание города'),
        ),
        migrations.AlterField(
            model_name='route',
            name='image_city1',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='image_city2',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='image_city3',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='image_city4',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='image_route1',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='image_route2',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='image_route3',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='image_route4',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='image_route5',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='image_route6',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
    ]
