# Generated by Django 4.2.16 on 2024-11-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_route_city_desc_alter_route_image_city1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('id',), 'verbose_name': 'Маршруты', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AddField(
            model_name='route',
            name='image_city5',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/city'),
        ),
        migrations.AddField(
            model_name='route',
            name='image_city6',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/city'),
        ),
    ]
