# Generated by Django 4.2.16 on 2024-11-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_alter_route_options_route_image_city5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='base_city_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Базовый город'),
        ),
        migrations.AddField(
            model_name='route',
            name='city_desc_2',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание города'),
        ),
        migrations.AddField(
            model_name='route',
            name='image_city10',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/city'),
        ),
        migrations.AddField(
            model_name='route',
            name='image_city11',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/city'),
        ),
        migrations.AddField(
            model_name='route',
            name='image_city12',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/city'),
        ),
        migrations.AddField(
            model_name='route',
            name='image_city7',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/city'),
        ),
        migrations.AddField(
            model_name='route',
            name='image_city8',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/city'),
        ),
        migrations.AddField(
            model_name='route',
            name='image_city9',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='image_city1',
            field=models.ImageField(blank=True, default='route_images/city/100.jpeg', null=True, upload_to='route_images/city'),
        ),
    ]
