# Generated by Django 4.2.16 on 2024-11-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_route_base_city_2_route_city_desc_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='slug_city_2',
            field=models.SlugField(blank=True, max_length=110, null=True, verbose_name='URL2'),
        ),
        migrations.AlterField(
            model_name='route',
            name='base_city_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Базовый город 2'),
        ),
        migrations.AlterField(
            model_name='route',
            name='city_desc_2',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание города 2'),
        ),
    ]
