# Generated by Django 4.2.16 on 2024-11-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_route_slug_city_2_alter_route_base_city_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='slug_city_2',
        ),
    ]
