# Generated by Django 4.2.16 on 2024-11-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_remove_route_slug_city_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='base_city_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Базовый город 3'),
        ),
    ]
