# Generated by Django 4.2.16 on 2024-12-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_route_base_city_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='image_route1',
            field=models.ImageField(blank=True, null=True, upload_to='media/route_images/route'),
        ),
    ]
