# Generated by Django 4.2.16 on 2024-12-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0011_alter_route_image_route1'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image_route10',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
        migrations.AddField(
            model_name='route',
            name='image_route11',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
        migrations.AddField(
            model_name='route',
            name='image_route12',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
        migrations.AddField(
            model_name='route',
            name='image_route7',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
        migrations.AddField(
            model_name='route',
            name='image_route8',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
        migrations.AddField(
            model_name='route',
            name='image_route9',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
    ]
