# Generated by Django 4.2.17 on 2024-12-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0012_route_image_route10_route_image_route11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image_route13',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
        migrations.AddField(
            model_name='route',
            name='image_route14',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
    ]
