# Generated by Django 4.2.17 on 2025-01-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0013_route_image_route13_route_image_route14'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='city_slug',
            field=models.SlugField(blank=True, max_length=110, null=True, verbose_name='URL_city'),
        ),
    ]
