# Generated by Django 4.2.17 on 2025-02-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0014_route_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image_route15',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
        migrations.AddField(
            model_name='route',
            name='image_route16',
            field=models.ImageField(blank=True, default='100.jpeg', null=True, upload_to='route_images/route'),
        ),
    ]
