# Generated by Django 4.2.17 on 2025-05-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0016_alter_route_city_desc_alter_route_city_desc_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('sort_order',), 'verbose_name': 'Маршруты', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AddField(
            model_name='route',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='Порядок сортировки'),
        ),
    ]
